/*
 * themes-list.js
 * GENERATED by tools/build_themes.py from the themes/ folder.
 * Do not edit by hand.
 */

/** Theme ids and display names, in picker order. */
window.QUIZ_THEMES = [
  ["classic", "Classic"],
  ["lego", "Lego"],
  ["clay", "Clay"],
  ["pastel", "Pastel"],
  ["comic", "Comic book"],
  ["whiteboard", "Whiteboard"],
  ["anime", "Anime"],
  ["watercolor", "Watercolor"],
  ["university", "University"],
  ["professional", "Professional"],
  ["vedic", "Vedic"],
  ["ayurveda", "Ayurveda"],
  ["history", "Indian History"],
  ["universe", "Universe"],
  ["maths", "Maths"],
  ["vmaths", "Vedic Maths"],
  ["geometry", "Geometry"],
  ["sanskrit", "Sanskrit"],
  ["exercise", "Exercise"],
  ["food", "Food"],
  ["yoga", "Yoga"],
  ["meditation", "Meditation"],
  ["brain", "Healthy Brain"],
  ["social", "Talk to People"],
  ["music", "Music"],
  ["art", "Art"]
];

/** The Google Fonts every theme needs, in one request. */
window.QUIZ_THEME_FONTS_URL =
  "https://fonts.googleapis.com/css2?" +
  [
    "family=Instrument+Sans:wght@400;500;600",
    "family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;1,8..60,400",
    "family=Fredoka:wght@400;500;600",
    "family=Nunito:wght@400;600;700",
    "family=Quicksand:wght@500;600;700",
    "family=Comic+Neue:wght@400;700",
    "family=Bangers",
    "family=Patrick+Hand",
    "family=Caveat:wght@600",
    "family=M+PLUS+Rounded+1c:wght@400;500;700",
    "family=EB+Garamond:wght@400;500;600",
    "family=Inter:wght@400;500;600",
    "family=Marcellus",
    "family=Cormorant+Garamond:wght@500;600",
    "family=Lora:wght@400;600",
    "family=Exo+2:wght@400;600",
    "family=Lexend:wght@400;500",
    "family=Baloo+2:wght@400;600",
    "family=Josefin+Sans:wght@400;600",
    "family=Barlow:wght@400;600",
    "family=Barlow+Condensed:wght@600",
    "family=Poppins:wght@400;500;600",
    "family=Playfair+Display:wght@500;700",
    "family=Permanent+Marker",
    "display=swap",
  ].join("&");
