#!/usr/bin/env python3
"""Build the theme files from the folders in themes/.

Run this after adding or changing a theme:

    python3 tools/build_themes.py

It reads every themes/<theme-id>/ folder and writes two generated files:

    css/themes.css       one block of CSS variables per theme and scheme,
                         the picker tile previews, and each theme's extra.css
    js/themes-list.js    the list of themes for the picker, and the
                         Google Fonts link the themes need

Never edit those two files by hand; your changes would be overwritten.

A theme folder contains:

    theme.json             name, fonts, shape, light and dark colours
    mascot.svg             the picture shown next to the book title
    start-icon.svg         the icon on the Start button (use currentColor)
    background-light.svg   optional, referenced from theme.json
    background-dark.svg    optional, referenced from theme.json
    extra.css              optional, any extra CSS for this theme only

See README.md ("Add a new theme") for a walk-through.
"""

import json
import re
from pathlib import Path
from urllib.parse import quote

SITE_FOLDER = Path(__file__).resolve().parent.parent
THEMES_FOLDER = SITE_FOLDER / "themes"
PICKER_ORDER_FILE = THEMES_FOLDER / "picker-order.txt"
THEMES_CSS_FILE = SITE_FOLDER / "css" / "themes.css"
THEMES_LIST_FILE = SITE_FOLDER / "js" / "themes-list.js"

GENERATED_WARNING = (
    "GENERATED by tools/build_themes.py from the themes/ folder. "
    "Do not edit by hand."
)

# How each colour in theme.json maps to a CSS variable.
COLOR_VARIABLES = {
    "page": "--color-page",
    "card": "--color-card",
    "text": "--color-text",
    "textMuted": "--color-text-muted",
    "border": "--color-border",
    "accent": "--color-accent",
    "accent2": "--color-accent-2",
    "highlight": "--color-highlight",
    "correct": "--color-correct",
    "wrong": "--color-wrong",
    "partly": "--color-partly",
    "pop1": "--color-pop-1",
    "pop2": "--color-pop-2",
    "pop3": "--color-pop-3",
    "pop4": "--color-pop-4",
    "onAccent": "--color-on-accent",
    "onHero": "--color-on-hero",
}

# Optional per-scheme values. When a theme leaves one out, the default in
# css/theme-base.css is used.
OPTIONAL_VARIABLES = {
    "buttonShadow": "--button-shadow",
    "buttonShadowPressed": "--button-shadow-pressed",
    "panelShadow": "--panel-shadow",
    "pressDepth": "--press-depth",
}

# Google Fonts the themes may use, with the weights to download.
# A font used in theme.json but missing here falls back to system fonts.
GOOGLE_FONTS = {
    "Instrument Sans": "Instrument+Sans:wght@400;500;600",
    "Source Serif 4": (
        "Source+Serif+4:ital,opsz,wght@"
        "0,8..60,400;0,8..60,600;1,8..60,400"
    ),
    "Fredoka": "Fredoka:wght@400;500;600",
    "Quicksand": "Quicksand:wght@500;600;700",
    "Comic Neue": "Comic+Neue:wght@400;700",
    "Bangers": "Bangers",
    "Patrick Hand": "Patrick+Hand",
    "Caveat": "Caveat:wght@600",
    "M PLUS Rounded 1c": "M+PLUS+Rounded+1c:wght@400;500;700",
    "Nunito": "Nunito:wght@400;600;700",
    "EB Garamond": "EB+Garamond:wght@400;500;600",
    "Inter": "Inter:wght@400;500;600",
    "Marcellus": "Marcellus",
    "Lora": "Lora:wght@400;600",
    "Cormorant Garamond": "Cormorant+Garamond:wght@500;600",
    "Exo 2": "Exo+2:wght@400;600",
    "Lexend": "Lexend:wght@400;500",
    "Baloo 2": "Baloo+2:wght@400;600",
    "Josefin Sans": "Josefin+Sans:wght@400;600",
    "Barlow": "Barlow:wght@400;600",
    "Barlow Condensed": "Barlow+Condensed:wght@600",
    "Poppins": "Poppins:wght@400;500;600",
    "Playfair Display": "Playfair+Display:wght@500;700",
    "Permanent Marker": "Permanent+Marker",
}

# The "next" arrow and the "check" tick drawn on buttons. Every theme
# shares the shapes; theme.json "iconStroke" sets how thick they are.
NEXT_ICON_PATH = "M4 12h14M12 5l7 7-7 7"
CHECK_ICON_PATH = "M4 12.5l5 5L20 6.5"


# ------------------------------------------------------------- reading


def read_picker_order():
    """Return theme ids in the order the picker should show them."""
    if not PICKER_ORDER_FILE.exists():
        return []
    lines = PICKER_ORDER_FILE.read_text().splitlines()
    return [line.strip() for line in lines
            if line.strip() and not line.startswith("#")]


def find_theme_ids():
    """Return every theme folder name, in picker order."""
    folder_names = sorted(
        folder.name for folder in THEMES_FOLDER.iterdir()
        if (folder / "theme.json").exists()
    )
    listed_first = [name for name in read_picker_order()
                    if name in folder_names]
    the_rest = [name for name in folder_names if name not in listed_first]
    return listed_first + the_rest


def load_theme(theme_id):
    """Read one theme folder into a dictionary."""
    folder = THEMES_FOLDER / theme_id
    theme = json.loads((folder / "theme.json").read_text())
    theme["id"] = theme_id
    theme["folder"] = folder
    extra_css_file = folder / "extra.css"
    theme["extraCss"] = (
        extra_css_file.read_text() if extra_css_file.exists() else ""
    )
    return theme


# ------------------------------------------------------------- svg


def svg_to_data_uri(svg_text, current_color=None):
    """Turn SVG text into a CSS url() that needs no separate file.

    current_color, when given, replaces the word currentColor, because an
    SVG inside a CSS url() cannot inherit the text colour.
    """
    if current_color:
        svg_text = svg_text.replace("currentColor", current_color)
    svg_text = re.sub(r"<\?xml[^>]*\?>", "", svg_text)
    svg_text = re.sub(r"\s+", " ", svg_text)
    svg_text = re.sub(r">\s+<", "><", svg_text).strip()
    encoded = quote(svg_text, safe=" /:=,;()'.-_")
    return f'url("data:image/svg+xml,{encoded}")'


def read_svg_as_data_uri(theme, file_name, current_color=None):
    """Read an SVG file from a theme folder as a CSS url()."""
    svg_text = (theme["folder"] / file_name).read_text()
    return svg_to_data_uri(svg_text, current_color)


def stroke_icon(path_data, stroke, color):
    """Draw a simple line icon (next arrow or check tick) as a url()."""
    svg_text = (
        "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'>"
        f"<path d='{path_data}' fill='none' stroke='{color}' "
        f"stroke-width='{stroke['width']}' "
        f"stroke-linecap='{stroke['cap']}' "
        f"stroke-linejoin='{stroke['join']}'/></svg>"
    )
    return svg_to_data_uri(svg_text)


# ------------------------------------------------------------- css values


def join_css_layers(layers):
    """Join theme.json layers into one CSS value.

    A layer is a string, or a list of pieces that are glued together
    (this lets long values stay on short lines in theme.json).
    """
    if isinstance(layers, str):
        return layers
    joined_layers = [
        "".join(layer) if isinstance(layer, list) else layer
        for layer in layers
    ]
    return ", ".join(joined_layers)


def inline_svg_files(css_value, theme):
    """Replace url(some-file.svg) with the file's contents."""
    def replace_file_with_contents(match):
        """The data URI for the file named in one url()."""
        return read_svg_as_data_uri(theme, match.group(1))
    return re.sub(r"url\(([\w-]+\.svg)\)", replace_file_with_contents,
                  css_value)


def page_background(theme, scheme):
    """The page background for one scheme, ready to use in CSS."""
    layers = join_css_layers(theme[scheme]["background"])
    return inline_svg_files(layers, theme)


def accent_gradient(colors):
    """A two-colour gradient, or a flat fill when both colours match."""
    if colors["accent"] == colors["accent2"]:
        return ("linear-gradient(var(--color-accent),"
                "var(--color-accent))")
    return ("linear-gradient(90deg,var(--color-accent),"
            "var(--color-accent-2))")


# ------------------------------------------------------------- css blocks


def theme_variables(theme, scheme):
    """Every CSS variable one theme sets for light or dark."""
    settings = theme[scheme]
    colors = settings["colors"]
    on_accent = colors["onAccent"]
    stroke = theme["iconStroke"]
    variables = {COLOR_VARIABLES[key]: value
                 for key, value in colors.items()}
    variables.update({
        "--font-body": theme["fonts"]["body"],
        "--font-heading": theme["fonts"]["headings"],
        "--radius": theme["shape"]["radius"],
        "--radius-small": theme["shape"]["smallRadius"],
        "--border-width": theme["shape"]["borderWidth"],
        "--border-width-strong": theme["shape"]["strongBorderWidth"],
        "--page-background": page_background(theme, scheme),
        "--mascot-image": read_svg_as_data_uri(theme, "mascot.svg"),
        "--icon-start": read_svg_as_data_uri(
            theme, "start-icon.svg", current_color=on_accent),
        "--icon-next": stroke_icon(NEXT_ICON_PATH, stroke, on_accent),
        "--icon-check": stroke_icon(CHECK_ICON_PATH, stroke, on_accent),
        "--accent-gradient": accent_gradient(colors),
    })
    for key, variable in OPTIONAL_VARIABLES.items():
        if key in settings:
            variables[variable] = join_css_layers(settings[key])
    return variables


def css_rule(selector, declarations):
    """Format one CSS rule with a declaration per line."""
    body = "".join(f"  {name}: {value};\n"
                   for name, value in declarations.items())
    return f"{selector} {{\n{body}}}\n"


def theme_variables_rule(theme, scheme):
    """The :root block that switches the page to this theme."""
    selector = (f":root[data-theme='{theme['id']}']"
                f"[data-scheme='{scheme}']")
    return css_rule(selector, theme_variables(theme, scheme))


def picker_tile_rules(theme):
    """CSS for this theme's preview tile in the theme picker.

    A tile shows the theme's own colours even while another theme is in
    use, so it gets its own small set of --tile-* variables.
    """
    rules = []
    for scheme in ("light", "dark"):
        colors = theme[scheme]["colors"]
        tile_background = page_background(theme, scheme).replace(
            "var(--color-page)", colors["page"])
        selector = f".theme-tile[data-theme-id='{theme['id']}']"
        if scheme == "dark":
            selector = "[data-scheme='dark'] " + selector
        rules.append(css_rule(selector, {
            "--tile-page": colors["page"],
            "--tile-card": colors["card"],
            "--tile-text": colors["text"],
            "--tile-border": colors["border"],
            "--tile-accent": colors["accent"],
            "--tile-on-accent": colors["onAccent"],
            "--tile-pop-1": colors["pop1"],
            "--tile-pop-2": colors["pop2"],
            "--tile-pop-3": colors["pop3"],
            "--tile-radius": theme["shape"]["smallRadius"],
            "--tile-background": tile_background,
        }))
    mascot_selector = (f".theme-tile[data-theme-id='{theme['id']}'] "
                       ".tile-mascot")
    rules.append(css_rule(mascot_selector, {
        "background-image": read_svg_as_data_uri(theme, "mascot.svg"),
    }))
    return "".join(rules)


# ------------------------------------------------------------- fonts


def font_family_names(theme):
    """The quoted family names in a theme's font settings."""
    font_settings = theme["fonts"]["body"] + theme["fonts"]["headings"]
    return re.findall(r'"([^"]+)"', font_settings)


def google_fonts_needed(themes):
    """The Google Fonts families the themes use, each listed once."""
    needed = []
    for theme in themes:
        for family in font_family_names(theme):
            if family in GOOGLE_FONTS and family not in needed:
                needed.append(family)
    return needed


def google_fonts_url_code(themes):
    """JavaScript that builds one Google Fonts link for every theme.

    Written as a list joined with "&" so each font sits on its own line.
    """
    url_parts = ["family=" + GOOGLE_FONTS[name]
                 for name in google_fonts_needed(themes)]
    url_parts.append("display=swap")
    parts_text = "".join(f"    {json.dumps(part)},\n" for part in url_parts)
    return (
        '  "https://fonts.googleapis.com/css2?" +\n'
        f"  [\n{parts_text}  ].join(\"&\")"
    )


# ------------------------------------------------------------- writing


def build_themes_css(themes):
    """The full text of css/themes.css."""
    parts = [f"/* themes.css: {GENERATED_WARNING} */\n\n"]
    for theme in themes:
        parts.append(f"/* ---------- {theme['name']} ---------- */\n")
        parts.append(theme_variables_rule(theme, "light"))
        parts.append(theme_variables_rule(theme, "dark"))
        parts.append(picker_tile_rules(theme))
        parts.append(theme["extraCss"])
        parts.append("\n")
    return "".join(parts)


def build_themes_list_js(themes):
    """The full text of js/themes-list.js."""
    picker_entries = [[theme["id"], theme["name"]] for theme in themes]
    entries_text = ",\n".join(
        f"  {json.dumps(entry)}" for entry in picker_entries)
    return (
        "/*\n * themes-list.js\n"
        " * GENERATED by tools/build_themes.py from the themes/ folder.\n"
        " * Do not edit by hand.\n */\n\n"
        "/** Theme ids and display names, in picker order. */\n"
        f"window.QUIZ_THEMES = [\n{entries_text}\n];\n\n"
        "/** The Google Fonts every theme needs, in one request. */\n"
        "window.QUIZ_THEME_FONTS_URL =\n"
        f"{google_fonts_url_code(themes)};\n"
    )


def main():
    themes = [load_theme(theme_id) for theme_id in find_theme_ids()]
    THEMES_CSS_FILE.write_text(build_themes_css(themes))
    THEMES_LIST_FILE.write_text(build_themes_list_js(themes))
    print(f"Built {len(themes)} themes into "
          f"{THEMES_CSS_FILE.relative_to(SITE_FOLDER)} and "
          f"{THEMES_LIST_FILE.relative_to(SITE_FOLDER)}")


if __name__ == "__main__":
    main()
